# [tooling]
# <Tooling-Web-Server-Private-IP-Address>


# [db:vars]
# ansible_user=ec2-user
# ansible_python_interpreter=/usr/bin/python

[nginx]
172.31.7.54 ansible_ssh_user='ec2-user'

[db]
44.199.216.41 ansible_ssh_user='ubuntu'

# [todo]
# 172.31.23.209 ansible_ssh_user='ec2-user'