pipeline {
    agent any
  stages {
    stage('build') {
      steps {
        script {
          sh 'echo "Testing Stage"'
        }
      }
    }
    stage('Test') {
      steps {
        script {
          sh 'echo "Testing Stage'
        }
      }
    }

}