pipeline {
  agent any

  stages {
      stage('Build') {
        steps {
          script {
            sh 'echo "Buillding stage"'
          }
        }
      }
      stage('Test') {
        steps {
          script {
            sh 'echo "Testing the stage"'
          }
        }
      }

      stage('Package') {
        steps {
          script {
            sh 'echo "Packaging the stage"'
          }
        }
      }
  }
}